// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ExamenTwitter
{
	public partial class TweetTableViewCell : UITableViewCell
	{

        public UIImage UserImage
        {
            get => ImgUser.Image;
            set => ImgUser.Image = value;
        }

        public string UserName
        {
            get => LblName.Text;
            set => LblName.Text = value;
        }

        public string FavoriteCount
        {
            get => LblFavoriteCount.Text;
            set => LblFavoriteCount.Text = value;
        }

        public string RetweetCount
        {
            get => LblRetweetCount.Text;
            set => LblRetweetCount.Text = value;
        }

        public string TweetDescription
        {
            get => TxtDescription.Text;
            set => TxtDescription.Text = value;
        }


        public TweetTableViewCell (IntPtr handle) : base (handle)
		{
            
		}
	}
}
